
enum RogueState
{
    IDLE = 0,
    RUNNING_TOWARDS_VICTIM,
    RUNNING_TOWARDS_PLAYER,
    WALKING_TOWARDS_VICTIM,
    LOOKING_FOR_VICTIM,
    LOOKING_FOR_VEHICLE,
    SHOOTING_AT_VICTIM,
    FIGHTING_ENEMY_PEDS
}